import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import PushNotificationManager from '@/components/PushNotificationManager';
import AndroidBackButton from '@/components/AndroidBackButton';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script dangerouslySetInnerHTML={{ __html: `
          if (typeof window !== 'undefined') {
            localStorage.setItem('driverToken', 'mock_jwt_token_for_srm_driver');
            localStorage.setItem('driver', JSON.stringify({ _id: '65f1a2b3c4d5e6f7a8b9c0d2', name: 'Rider Rahul' }));
          }
        ` }} />
        <AndroidBackButton />
        <PushNotificationManager />
        {children}
      </body>
    </html>
  );
}
